"use client";

import { Switch } from "@/components/ui/switch";
import Spline from "@splinetool/react-spline";
import { ThemeProvider, useTheme } from "next-themes";
import Image from "next/image";
import Link from "next/link";
import { ChevronRight } from "lucide-react";

export default function Home() {
  const { theme, setTheme } = useTheme();

  return (
    <div className="w-full flex flex-col space-y-16 max-w-screen-md relative pb-32">
      <div className="aspect-video max-h-[40rem] w-full relative">
        <Image
          src="/philanthro-threads.png"
          alt="Philanthro Threads Hero"
          fill
          className="object-cover object-top    "
        />
        
      </div>

      <section className="px-4 flex flex-col relative space-y-6">
        <div className="flex space-x-4 items-center">
          <h1 className="text-4xl font-semibold">Philanthro-Threads</h1>
          <Switch
            className="mt-2"
            checked={theme === "dark"}
            onCheckedChange={(checked) => setTheme(checked ? "dark" : "light")}
          />
        </div>
        <p className="text-sm mb-8 font-medium">
          Philanthro Threads was an idea I had to create a platform that sells
          clothing with unique prints generated by AI. I developed many tools to
          generate prompts, stories, characters, artwork, and then process the
          artwork using python. I then created an ecommerce site with next.js
          and stripe, with a second backend in django to work with the python
          tools I created. I eventually scrapped the project because I did not
          care to market it, but still have the original collection of artwork "surreal safari".
        </p>
        <p className="text-xs mb-8 font-medium font-mono ">
          {/* <a
            href="https://knowledgetoforage.com/"
            className="underline"
            target="_blank"
          > */}
          Site is no longer live
          {/* </a> */}
        </p>
        <Link
          href="/"
          className=" max-w-fit  bg-primary text-primary-foreground px-6 py-2 rounded-md hover:bg-primary/90 transition-colors"
        >
          Go Back
        </Link>

        <h2 className="text-2xl font-regular font-semibold">Image Generation:</h2>
        <p className="text-sm font-medium">
          The image generation pipeline utilized various AI models and automation tools. I developed
          a Django backend that orchestrated the generation process using Generative AI models.
          Selenium was integrated for automated batch processing and content generation, allowing
          for scalable creation of unique artwork for the apparel designs.
        </p>

        <h2 className="text-2xl font-regular mb-6 font-semibold">Image Processing:</h2>
        <p className="text-sm font-medium">
          Raw generated images were enhanced using Real-ESRGAN for upscaling and quality improvement.
          Python's PIL (Pillow) library was used for additional image processing tasks such as
          format conversion, resizing, and optimization for web display. This ensured all artwork
          met the quality standards required for print-on-demand services.
        </p>

        <h2 className="text-2xl font-regular mb-6 font-semibold">Print On Demand Integration:</h2>
        <p className="text-sm font-medium">
          The platform was designed to seamlessly integrate with print-on-demand services.
          Each processed artwork was automatically formatted to meet various product specifications,
          ensuring high-quality prints across different apparel types. The system included
          automated mock-up generation and product variant creation.
        </p>

        <h2 className="text-2xl font-regular mb-6 font-semibold">Ecommerce Site:</h2>
        <p className="text-sm font-medium">
          The frontend was built using Next.js, prioritizing performance through server-side
          rendering and optimized data fetching. Firebase was integrated for real-time updates
          and dynamic content management. 
        </p>
      </section>
    </div>
  );
}
