"use client";

import { Switch } from "@/components/ui/switch";
import Spline from "@splinetool/react-spline";
import { ThemeProvider, useTheme } from "next-themes";
import Image from "next/image";
import Link from "next/link";
import { ChevronRight } from "lucide-react";

export default function Home() {
  const { theme, setTheme } = useTheme();

  return (
    <div className="w-full flex flex-col space-y-16 max-w-screen-md relative pb-32">
      <div className="aspect-video max-h-[40rem] w-full relative">
        <Image
          src="/philanthro-threads.png"
          alt="Philanthro Threads Hero"
          fill
          className="object-cover object-top    "
        />
      </div>

      <section className="px-4 flex flex-col relative space-y-6">
        <div className="flex space-x-4 items-center">
          <h1 className="text-4xl font-semibold">Philanthro-Threads</h1>
          <Switch
            className="mt-2"
            checked={theme === "dark"}
            onCheckedChange={(checked) => setTheme(checked ? "dark" : "light")}
          />
        </div>
        <p className="text-sm mb-8 font-medium ">
          Philantrho Threads was an idea I had to create a platform that sells
          clothing with unique prints generated by AI. I developed many tools to
          generate prompts, stories, characters, artwork, and then process the
          artwork using python. I then created an ecommerce site with next.js
          and stripe, with a second backend in django to work with the python
          tools I created. I evenutally scrapped the project because I did not
          care to market it, but still have the original collection of artwork "surreal safari".
        </p>
        <p className="text-xs mb-8 font-medium font-mono ">
          {/* <a
            href="https://knowledgetoforage.com/"
            className="underline"
            target="_blank"
          > */}
          Site is no longer live
          {/* </a> */}
        </p>
        <Link
          href="/"
          className=" max-w-fit  bg-primary text-primary-foreground px-6 py-2 rounded-md hover:bg-primary/90 transition-colors"
        >
          Go Back
        </Link>

        <h2 className="text-2xl font-regular  font-semibold">Image Generation:</h2>
        <p>

        </p>
        <h2 className="text-2xl font-regular mb-6 font-semibold">Image Processing:</h2>
        <p>

        </p>
        <h2 className="text-2xl font-regular mb-6 font-semibold">Print On Demand Integration:</h2>
        <p>

        </p>
        <h2 className="text-2xl font-regular mb-6 font-semibold">Ecommerce Site:</h2>
        <p>

        </p>
      </section>
    </div>
  );
}
